#!/bin/bash

# parameters - name link

dir="$HOME/.config/.bashmark"
mainfile="$dir/.main"
[ ! -d $dir ] && mkdir -p $dir
[ ! -f $mainfile ] && touch $mainfile
function add()
{
	linkname=$(printf "" | dmenu -p "Name:")
	case $linkname in
	"")
	exit
	;;
	esac


	if grep -wq "$linkname" "$mainfile"
	then
		notify-send "Error: Name used" "Click to dismiss."
		exit
	fi

	link=$(printf "" | dmenu -p "Link:")
	case $link in
	"")
	exit
	;;
	esac


	[[ "$link" != https://* && $link != http://* ]] && protocol=$(printf "Http\nHttps" | dmenu) && link=$(printf "$protocol"  | tr '[:upper:]' '[:lower:]')://$link

	if grep -wq "$link" "$mainfile"
	then
		notify-send "Error: Link used" "Click to dismiss."
		exit
	fi

	printf '%s %s\n' "$linkname" "$link" >> "$mainfile"
}

function get()
{
	trg=$(cat "$mainfile" | awk '{print $1}' | sort | dmenu -i -p "Bashmark")
	if [ "$trg" != "" ]; then
		grep -w "$trg" "$mainfile" | awk '{print $2}' | xclip -selection clipboard
		notify-send "💻 $trg copied to the clipboard." "Click to dismiss."
	fi
}
menu=$(printf "Add\nGet" | dmenu -i -p "Bashmark")

case $menu in
"Add")
add
;;
"Get")
get
;;
*)
exit
;;
esac
