#!/bin/bash
gpu="amdgpu_bl1"
file="/sys/class/backlight/$gpu/brightness"
statsresult=$((($(cat $file) * 100) / 255))
case $1 in
"-s")
if (( $2 <= 100 && $2 >= 0 )); then
	clear
	results=$((($2 * 255) / 100))
	sudo echo "$results" > "$file"
fi
echo "$2"
;;
*) printf "%s" "☀️ $statsresult%"
;;
esac
