#!/bin/bash
# Usage:
#  $0        $1			   $2
# notes		options		inputfile
PS3="> "
NOTE_DIR="$HOME/Notes/"
DIR="$HOME/Notes/Reading/"
fmn=( "Presentation" "Pdf" );
input=$2

[ ! -d $DIR ] && mkdir -p "$DIR"
[ -z "$input" ] && input="notes-$(date '+%Y-%m-%d-%H:%M').md"
[[ "$input" != *.md ]] && input=$input.md

case $1 in
"-c") printf --  '---\ntitle:\n- A great title\nauthor:\n- An even greater author\n---\n# This is a note\n## This is the start of your note!\n' > "$NOTE_DIR$input"
vim "$NOTE_DIR$input"
;;
"-f")
[ -z "$2" ] && exit 1
select choice in "${fmn[@]}"; do
	case $choice in
	"Presentation") pandoc $input -t beamer -o "$DIR${input//.md}.pdf" ; exit 0 ;;
	"Pdf") pandoc -s -o "$DIR${input//.md}.pdf" $input ; exit 0 ;;
	esac
done ;;
*) printf "Options:\n-c\tCreate a new note\n-f\tFormat a note\nUsage:\nnotes option inputfile\n" ;;
esac
