#!/bin/bash
# Usage:
#  $0        $1			   $2
# notes		options		inputfile
Editor=vim
PS3="> "
categories=$(ls -p $HOME/Notes/ | grep /)
NOTE_DIR="$HOME/Notes/"
fmn=( "Presentation" "Pdf" );
input=$2
n=$(find $NOTE_DIR -type f | sed 's/\.\///' | sed 's/^.*\(Notes.*\)/\1/g' | sed "s/Notes\///g" | grep .md$)
input=$($input | sed "s/\//&/g")

[ -z "$input" ] && input="notes-$(date '+%Y-%m-%d-%H:%M').md"
[[ "$input" != *.md ]] && input=$input.md

case $1 in
"-s")
select option in $n
do
	[ -z "$option" ] && exit 1
	cd $NOTE_DIR
	$Editor $option
	exit 0
done
exit 0 ;;
"-c")
read -p "Category? (Y/N): " catchoice
[ -z $catchoice ] && exit 1
case $catchoice in
"Y")
read -p 'New? (Y/N): ' new
[ -z $new ] && exit 1
case $new in
"Y")
read -p "Category: " newcat
[ -z $newcat ] && exit 1
newcat=$($newcat | sed "s/\//&/g")
mkdir $NOTE_DIR$newcat
printf --  '---\ntitle:\n- A great title\nauthor:\n- An even greater author\ndate:\n- ' > "$NOTE_DIR$newcat/$input"
printf -- $(date +%d/%m/%Y) >> "$NOTE_DIR$newcat/$input"
printf -- '\ntheme:\n- Berlin\ncolortheme:\n- default\ncomment:\n- This is my awesome comment\n---\n# This is a note\n## This is the start of your note!\n' >> "$NOTE_DIR$newcat/$input"
$Editor "$NOTE_DIR$newcat/$input"
exit 0
;;
esac
select option in $categories; do
	[ -z $option ] && exit 1
	printf --  '---\ntitle:\n- A great title\nauthor:\n- An even greater author\ndate:\n- ' > "$NOTE_DIR$option/$input"
	printf -- $(date +%d/%m/%Y) >> "$NOTE_DIR$option/$input"
	printf -- '\ntheme:\n- Berlin\ncolortheme:\n- default\ncomment:\n- This is my awesome comment\n---\n# This is a note\n## This is the start of your note!\n' >> "$NOTE_DIR$option/$input"
	$Editor "$NOTE_DIR$option/$input"
	exit 0
done
;;
*)
printf --  '---\ntitle:\n- A great title\nauthor:\n- An even greater author\ndate:\n- ' > "$NOTE_DIR$input"
printf -- $(date +%d/%m/%Y) >> "$NOTE_DIR$input"
printf -- '\ntheme:\n- Berlin\ncolortheme:\n- default\ncomment:\n- This is my awesome comment\n---\n# This is a note\n## This is the start of your note!\n' >> "$NOTE_DIR$input"
$Editor "$NOTE_DIR$input"
exit 0
;;
esac
;;
"-f")
select option in $n
do
	[ -z "$option" ] && exit 1
	cd $NOTE_DIR
	select choice in "${fmn[@]}"; do
	case $choice in
	"Presentation") pandoc $option -t beamer -o "${option//.md}.pdf" ; exit 0 ;;
	"Pdf") pandoc --pdf-engine=xelatex -s -o "${option//.md}.pdf" $option ; exit 0 ;;
	esac
	done
	exit 0
done
exit 0 ;;
*) printf "Options:\n-s\tEdit note\n-c\tCreate a new note\n-f\tFormat a note\nUsage:\nnotes option inputfile\n" ;;
esac
