#!/bin/bash

wording=""
options=""
screenshotdirs="$HOME/Images/Screenshots/"

function nodel()
{
	scrot $options "$path"
	notify-send "Screenshot taken" "Saved in: $path"
}

function del()
{
	notify-send "$wording" "Click to dismiss"
	scrot $options "$path"
	notify-send "Screenshot taken" "Saved in: $path"
}

function fullscreen()
{
	delmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case "$delmenu" in
	"No delay")
	options="" ; nodel ;;
	"Delay")
	delfullchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delfullchoice" in
	"5s") wording="5 seconds" ; options="-d 5" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*) exit ;;
	esac
}

function partial()
{
	delpartmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case "$delpartmenu" in
	"No delay") options="-bs" ; nodel ;;
	"Delay")
	delpartchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delpartchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -bs" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -bs" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -bs" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -bs" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -bs" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -bs" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -bs" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -bs" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -bs" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -bs" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -bs" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	esac
}

function window()
{
	acwinmenu=$(printf "Active window\nSelect window" | dmenu -i -p "Screentake")
	case "$acwinmenu" in
	"Active window")
	bordwinmenu=$(printf "Border\nNo border" | dmenu -i -p "Screentake")
	case "$bordwinmenu" in
	"Border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay") options="-ub" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -ub" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -ub" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -ub" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -ub" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -ub" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -ub" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -ub" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -ub" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -ub" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -ub" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -ub" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	"No border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay") options="-u" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -u" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -u" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -u" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -u" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -u" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -u" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -u" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -u" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -u" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -u" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -u" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	esac
	;;
	"Select window")
	bordwinmenu=$(printf "Border\nNo border" | dmenu -i -p "Screentake")
	case $bordwinmenu in
	"Border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay")
	options="-sb" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -sb" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -sb" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -sb" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -sb" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -sb" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -sb" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -sb" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -sb" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -sb" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -sb" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -sb" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	"No border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay") options="-s" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -s" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -s" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -s" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -s" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -s" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -s" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -s" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -s" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -s" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -s" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -s" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	esac
}

if [ ! -d "$screenshotdirs" ]; then
	mkdir -p $screenshotdirs
fi



main() {
	menu=$(printf "Fullscreen\nPartial\nWindow" | dmenu -i -p "Screentake")
	[ -z "$menu" ] && exit 1
	filename=$(printf "" | dmenu -p "Filename:")
	[ ! -z "$filename" ] && filename="screen_%Y-%m-%d_%H-%M-%S"
	[[ $filename != *.png ]] || [[ $filename != *.jpg ]] || [[ $filename != *.jpeg ]] && filename="$filename.png"
	path="$screenshotdirs$filename"
	case $menu in
	"Partial")
	partial
	;;
	"Window")
	window
	;;
	"Fullscreen")
	fullscreen
	;;
	*)
	exit
	;;
	esac

}

# Start
main
