#!/bin/bash

# NOT FINISHED
# STILL OPTIMIZING

wording=""
choicepath=""
options=""

screenshotdirs="$HOME/Images/Screenshots/"
logfile="$HOME/.sctsaker"

function nodel()
{
	scrot $options "$choicepath"
	notify-send "Screenshot taken" "Saved in: $choicepath"
}

function del()
{
	notify-send "$wording" "Click to dismiss"
	scrot $options "$choicepath"
	notify-send "Screenshot taken" "Saved in: $choicepath"
}

function defpath()
{
	mkdir -p "$screenshotdirs"
	printf "$screenshotdirs" >> $logfile
}

function fullscreen()
{
	fullchoice=$(printf "" | dmenu -p "Filename:")
	[ "$fullchoice" = "" ] && fullchoice="screen_%Y-%m-%d_%H-%M-%S"
	[[ $fullchoice != *.png ]] || [[ $fullchoice != *.jpg ]] || [[ $fullchoice != *.jpeg ]] && fullchoice="$fullchoice.png"
	choicepath="$shotpath$fullchoice"
	delmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case "$delmenu" in
	"No delay")
	options="" ; nodel ; scrot "$shotpath$fullchoice" ;;
	"Delay")
	delfullchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delfullchoice" in
	"5s") wording="5 seconds" ; options="-d 5" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*) exit ;;
	esac
}

function partial()
{
	partialchoice=$(printf "" | dmenu -p "Filename:")
	[ "$partialchoice" = "" ] && partialchoice="screen_%Y-%m-%d_%H-%M-%S"
	[[ $partialchoice != *.png ]] || [[ $partialchoice != *.jpg ]] || [[ $partialchoice != *.jpeg ]] && partialchoice="$partialchoice.png"
	choicepath="$shotpath$partialchoice"
	delpartmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case "$delpartmenu" in
	"No delay") options="-bs" ; nodel ;;
	"Delay")
	delpartchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delpartchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -bs" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -bs" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -bs" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -bs" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -bs" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -bs" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -bs" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -bs" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -bs" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -bs" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -bs" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	esac
}

function window()
{
	winchoice=$(printf "" | dmenu -p "Filename:")
	[ "$winchoice" = "" ] && winchoice="screen_%Y-%m-%d_%H-%M-%S"
	[[ $winchoice != *.png ]] || [[ $winchoice != *.jpg ]] || [[ $winchoice != *.jpeg ]] && winchoice="$winchoice.png"
	choicepath="$shotpath$winchoice"
	acwinmenu=$(printf "Active window\nSelect window" | dmenu -i -p "Screentake")
	case "$acwinmenu" in
	"Active window")
	bordwinmenu=$(printf "Border\nNo border" | dmenu -i -p "Screentake")
	case "$bordwinmenu" in
	"Border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay") options="-ub" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -ub" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -ub" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -ub" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -ub" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -ub" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -ub" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -ub" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -ub" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -ub" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -ub" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -ub" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	"No border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay") options="-u" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -u" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -u" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -u" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -u" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -u" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -u" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -u" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -u" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -u" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -u" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -u" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	esac
	;;
	"Select window")
	bordwinmenu=$(printf "Border\nNo border" | dmenu -i -p "Screentake")
	case $bordwinmenu in
	"Border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay")
	options="-sb" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -sb" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -sb" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -sb" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -sb" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -sb" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -sb" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -sb" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -sb" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -sb" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -sb" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -sb" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	"No border")
	delwinmenu=$(printf "Delay\nNo delay" | dmenu -i -p "Screentake")
	case $delwinmenu in
	"No delay") options="-s" ; nodel ;;
	"Delay")
	delwinchoice=$(printf "5s\n10s\n20s\n45s\n1m\n1.5m\n2m\n3m\n5m\n7m\n10m" | dmenu -i -p "Delay:")
	case "$delwinchoice" in
	"5s") wording="5 seconds" ; options="-d 5 -s" ; del ; exit 0 ;;
	"10s") wording="10 seconds" ; options="-d 10 -s" ; del  ; exit 0 ;;
	"20s") wording="20 seconds" ; options="-d 20 -s" ; del  ; exit 0 ;;
	"45s") wording="45 seconds" ; options="-d 45 -s" ; del  ; exit 0 ;;
	"1m") wording="1 minute" ; options="-d 60 -s" ; del  ; exit 0 ;;
	"1.5m") wording="1.5 minutes" ; options="-d 90 -s" ; del  ; exit 0 ;;
	"2m") wording="2 minutes" ; options="-d 120 -s" ; del  ; exit 0 ;;
	"3m") wording="3 minutes" ; options="-d 180 -s" ; del  ; exit 0 ;;
	"5m") wording="5 minutes" ; options="-d 300 -s" ; del  ; exit 0 ;;
	"7m") wording="7 minutes" ; options="-d 420 -s" ; del  ; exit 0 ;;
	"10m") wording="10 minutes" ; options="-d 600 -s" ; del  ; exit 0 ;;
	*) exit ;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	*)
	exit
	;;
	esac
	;;
	esac
}

shotpath="$(cat $logfile)"

if [ -f "$logfile" ]
then
	if [ "$(cat $logfile)" != "" ]
	then
		if [ ! -d "$(cat $logfile)" ]
		then
			rm $logfile
			touch $logfile
			defpath
		fi
	else
		screenpath=$(printf "" | dmenu -p "Screenshot Path:")
		if [ -d "$screenpath" ]
		then
			printf "$screenpath" >> $logfile
		else
			pathmen=$(printf "Create it\nCancel" | dmenu -i -p "Dir doesnt exist")
			if [ $pathmen = "Create it" ]
			then
				mkdir -p "$screenpath"
				printf "$screenpath" >> $logfile
			else
				defpath
			fi
		fi
			
	fi
	printf ""
else 
	touch $logfile
	scpath=$(printf "" | dmenu -p "Screenshot Path:")
	if [ -d "$scpath" ]
	then
		printf "$scpath" >> $logfile
	else
		pathmenu=$(printf "Create it\nCancel" | dmenu -i -p "Dir doesnt exist")
		if [ $pathmenu = "Create it" ]
		then
			mkdir -p "$scpath"
			printf "$scpath" >> $logfile
		else
			mkdir -p $HOME/Images/Screenshots/
			printf "$HOME/Images/Screenshots/" >> $logfile
		fi
	fi
fi

menu=$(printf "Fullscreen\nPartial\nWindow" | dmenu -i -p "Screentake")

case $menu in
"Partial")
partial
;;
"Window")
window
;;
"Fullscreen")
fullscreen
;;
*)
exit
;;
esac
