#!/bin/bash
# Usage: vpn -s / connect / vpn -d / disconnect

case $1 in
"-c") sudo protonvpn c -f ; protonvpn status ;;
"-d") sudo protonvpn disconnect ; protonvpn status ;;
"-s") protonvpn status ;;
*) printf "Usage:\nvpn -c : connect\nvpn -d : disconnect\nvpn -s : status\n" ;;
esac
